name: Lab02 workflow

on:
    push:
        branches:
            - main
            
jobs:
    # You can use any name for this, but ensure that it make sense and easy to understand
    unittest: 
        name: Unit Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3 #Use checkout action to download the source code to run unittest
              name: Checkout
            - uses: actions/setup-go@v3 #Setup golang environment for runnint unittest
              name: Setup Go environment
              with:
                go-version-file: ./src/go.mod
            - name: Run Unit Test
              working-directory: ./src
              run: go test ./...
